# Default values for keycloak.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: ghcr.io/h4d1s/keycloak
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account.
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template.
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # This sets the service type more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types
  type: ClusterIP
  # This sets the ports more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports
  port: 80

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: auth.rent-acme.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

# -- Expose the service via gateway-api HTTPRoute
# Requires Gateway API resources and suitable controller installed within the cluster
# (see: https://gateway-api.sigs.k8s.io/guides/)
httpRoute:
  # HTTPRoute enabled.
  enabled: false
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
  - name: gateway
    sectionName: http
    # namespace: default
  # Hostnames matching HTTP header.
  hostnames:
  - chart-example.local
  # List of rules and filters applied.
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /headers
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /health/live
    port: 9000
  initialDelaySeconds: 60
  failureThreshold: 60
  periodSeconds: 5
readinessProbe:
  httpGet:
    path: /health/ready
    port: 9000
  initialDelaySeconds: 30
  failureThreshold: 60
  periodSeconds: 5
startupProbe:
  httpGet:
    path: /health/ready
    port: 9000
  failureThreshold: 60
  periodSeconds: 5

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes:
  - name: realm-config
    configMap:
      name: keycloak-config-realm

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: realm-config
    mountPath: /opt/keycloak/data/import/realm-rent-acme.json
    subPath: realm-rent-acme.json

nodeSelector: {}

tolerations: []

affinity: {}

args:
  - start
  - --import-realm

env:
  - name: KC_HOSTNAME
    value: ""
  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HOSTNAME_STRICT
    value: "false"
  - name: KC_PROXY
    value: edge
  - name: KC_PROXY_HEADERS
    value: xforwarded

  - name: KC_DB
    value: postgres
  - name: KC_DB_URL_HOST
    value: keycloak-db.infra-databases.svc.cluster.local
  - name: KC_DB_URL_DATABASE
    value: keycloak_db
  - name: KC_DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_DB_USERNAME
  - name: KC_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_DB_PASSWORD

  - name: KC_BOOTSTRAP_ADMIN_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_BOOTSTRAP_ADMIN_USERNAME
  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KC_BOOTSTRAP_ADMIN_PASSWORD

  - name: KK_TO_RMQ_URL
    value: rabbitmq.infra-messaging.svc.cluster.local
  - name: KK_TO_RMQ_PORT
    value: 5672
  - name: KK_TO_RMQ_USERNAME
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KK_TO_RMQ_USERNAME
  - name: KK_TO_RMQ_PASSWORD
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KK_TO_RMQ_PASSWORD
  - name: KK_TO_RMQ_EXCHANGE
    value: amq.topic
  - name: KK_TO_RMQ_VHOST
    value: /

  - name: KC_OTEL
    value: "true"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://otel-collector.infra-observability.svc.cluster.local:4317"
  - name: OTEL_LOGS_EXPORTER
    value: otlp
  - name: OTEL_EXPORTER_OTLP_PROTOCOL
    value: grpc

  - name: KEYCLOAK_BACKEND_SECRET
    valueFrom:
      secretKeyRef:
        name: keycloak-secrets
        key: KEYCLOAK_BACKEND_SECRET

  - name: KC_HTTP_ENABLED
    value: "true"
  - name: KC_HTTP_PORT
    value: "80"

  - name: KC_HEALTH_ENABLED
    value: "true"