@hostname = localhost
@port = 5212
@baseUrl = https://{{hostname}}:{{port}}/api/v1
@contentType = application/json

# --- Identity Provider Configuration ---
@keycloakUrl = http://localhost:8080
@realm = rent-acme

### IDENTITY: Get Access Token
# @name login
POST {{keycloakUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=client&username=rent-acme-admin&password=Passw0rd!

### Capture the token
@authToken = {{login.response.body.$.access_token}}

### Get a User
# @no-ssl-verify
GET {{baseUrl}}/users/019dc31d-6b92-7e67-a57b-b381eddbb495
Authorization: Bearer {{authToken}}
Accept: {{contentType}}

### Update a User
# @no-ssl-verify
PUT {{baseUrl}}/users/6F31CC35-8F8B-4A1A-F047-08DE9EB97C9F
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
  "id": "6F31CC35-8F8B-4A1A-F047-08DE9EB97C9F",
  "email": "customer2@rent-acme.com",
  "userName": "jdoe",
  "firstName": "John",
  "lastName": "Doe",
  "phoneNumber": "+1234567890",
  "street": "123 Main St",
  "city": "Washington",
  "postalCode": "12345",
  "country": "USA"
}

### Delete a User
# @no-ssl-verify
DELETE {{baseUrl}}/users/6F31CC35-8F8B-4A1A-F047-08DE9EB97C9F
Authorization: Bearer {{authToken}}