apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: {{ .Values.secrets.GF_SECURITY_ADMIN_USER | quote }}
  GF_SECURITY_ADMIN_PASSWORD: {{ .Values.secrets.GF_SECURITY_ADMIN_PASSWORD | quote }}