apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabbitmq.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: {{ .Values.secrets.RABBITMQ_DEFAULT_USER | quote }}
  RABBITMQ_DEFAULT_PASS: {{ .Values.secrets.RABBITMQ_DEFAULT_PASS | quote }}