secrets:
  ConnectionStrings__RabbitMQ: "amqp://rent-acme:Passw0rd!@rabbitmq.infra-messaging.svc.cluster.local"
  ConnectionStrings__SagaMachineContext: "Host=saga-orchestration-statemachine-db.infra-databases.svc.cluster.local;Database=saga_machine_db;User Id=rent-acme;Password=Passw0rd!;"
  KEYCLOAK_BACKEND_SECRET: "7f1c9d84-3a52-4e7b-8c19-5d2a47f6b381"
