apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.secrets.REDIS_PASSWORD | quote }}