apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_USERNAME: {{ .Values.secrets.KC_BOOTSTRAP_ADMIN_USERNAME | quote }}
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ .Values.secrets.KC_BOOTSTRAP_ADMIN_PASSWORD | quote }}
  KC_DB_USERNAME: {{ .Values.secrets.KC_DB_USERNAME | quote }}
  KC_DB_PASSWORD: {{ .Values.secrets.KC_DB_PASSWORD | quote }}
  KK_TO_RMQ_USERNAME: {{ .Values.secrets.KK_TO_RMQ_USERNAME | quote }}
  KK_TO_RMQ_PASSWORD: {{ .Values.secrets.KK_TO_RMQ_PASSWORD | quote }}
  KEYCLOAK_BACKEND_SECRET: {{ .Values.secrets.KEYCLOAK_BACKEND_SECRET | quote }}