apiVersion: v1
kind: Secret
metadata:
  name: {{ include "inventory-api.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ConnectionStrings__RabbitMQ: {{ .Values.secrets.ConnectionStrings__RabbitMQ | quote }}
  ConnectionStrings__InventoryDbContext: {{ .Values.secrets.ConnectionStrings__InventoryDbContext | quote }}
  ConnectionStrings__Redis: {{ .Values.secrets.ConnectionStrings__Redis | quote }}
  KEYCLOAK_BACKEND_SECRET: {{ .Values.secrets.KEYCLOAK_BACKEND_SECRET | quote }}