receivers:
  otlp:
    protocols:
      grpc:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlphttp/tempo:
    endpoint: "http://tempo:4318"
    tls:
      insecure: true
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    tls:
      insecure: true
  prometheus:
    endpoint: "otel-collector:8889"

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check, pprof, zpages]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, loki]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, prometheus]