apiVersion: v1
kind: Secret
metadata:
  name: {{ include "payment-api.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ConnectionStrings__RabbitMQ: {{ .Values.secrets.ConnectionStrings__RabbitMQ | quote }}
  KEYCLOAK_BACKEND_SECRET: {{ .Values.secrets.KEYCLOAK_BACKEND_SECRET | quote }}