apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317

    processors:
      batch:

    exporters:
      debug:
        verbosity: detailed
      otlp_http/tempo:
        endpoint: http://tempo.infra-observability.svc.cluster.local:4318
        tls:
          insecure: true
      otlp_http/logs:
        endpoint: http://loki.infra-observability.svc.cluster.local:3100/otlp
        tls:
          insecure: true
        headers:
          X-Scope-OrgID: "fake"
      prometheus:
        endpoint: 0.0.0.0:8889

    extensions:
      health_check:
        endpoint: 0.0.0.0:13133
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    service:
      extensions: [health_check, pprof, zpages]
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlp_http/tempo]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlp_http/logs]
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, prometheus]