name: CD

on:
  push:
    branches:
      - master
      - dev
      - "release/**"
    tags:
      - 'v*'

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
  KEYCLOAK_BACKEND_SECRET: ${{ secrets.KEYCLOAK_BACKEND_SECRET }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build and Test
      run: |
        dotnet build -c Release
        dotnet test -c Release

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push with Compose
      working-directory: ./src
      env:
        DOCKER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}/
      run: |
        docker compose build
        docker compose push