name: CD

on:
  push:
    branches:
      - master
      - dev
      - "release/**"
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

env:
  DOCKER_USER: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_REGISTRY: ghcr.io/${{ github.repository_owner }}/
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
  KEYCLOAK_BACKEND_SECRET: ${{ secrets.KEYCLOAK_BACKEND_SECRET }}

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Build and Test
      run: |
        dotnet build -c Release
        dotnet test -c Release

    - name: Docker Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push with Compose
      working-directory: ./src
      run: |
        docker compose build
        docker compose push